### ISSUE TITLE
Container -- bad CPU type in executable

### ISSUE THREAD

**Issue by boreek** [Southclaws/sampctl#321]
Hi,
assembly operation error in the container
(macOS 10.15.1)

Start assembly
`sampctl package run --container`

Throws such an error
`failed to prepare package for running: failed to compile package entry: failed to execute compiler: fork/exec /Users/hacker/.samp/pawn/3.10.9/pawncc: bad CPU type in executable`

This appeared after updating the macOS from version 14 to 15

**Comment by Y-Less** [comment]
If that's the latest mac they disabled x86 programs.  Get a good OS*.


\* The purpose of an operating system is to run the programs you want to run.  Therefore an OS that can't do this is by definition a bad one.

**Comment by boreek** [comment]
// docker-compose.yml

```yml
version: '3'
services:
  sampctl:
    image: southclaws/sampctl:latest
    volumes:
      - ./:/samp
```

**Run:**
`docker-compose run sampctl p run --watch`


It's help me to run sampctl on macOS 10.15
